Revert "[MRP-176] get_ec_devno() in libecho mishandles results"
This reverts commit bc80e4da518e1a556084d95a0e44dd7b244ef612.

diff --git a/lustre-iokit/obdfilter-survey/libecho b/lustre-iokit/obdfilter-survey/libecho
--- a/lustre-iokit/obdfilter-survey/libecho
+++ b/lustre-iokit/obdfilter-survey/libecho
@@ -248,38 +248,34 @@ cleanup () {
 trap cleanup SIGHUP SIGINT SIGTERM
 
 # gets echoclient device number and attach it to the client UUID
-# Results are  returned by an echo followed by an exit
-# This must run in a subshell.
-#
+# 
 # parameter: 1. hostname
 #	     2. client name, ex:- ns8:ECHO_ns8
 #	     3. name of ost instances, ex:- lustre-OST0001 
 get_ec_devno () {
-    exec 8>&1 1>&2
     local host=$1
     local client_name="$2"
     local ost_name="$3"
     if [ -z "$client_name" ]; then
 	if [ -z "$ost_name" ]; then
-	    echo "client and ost name both null"
-	    exit 1
+	    echo "client and ost name both null" 1>&2
+	    return
 	fi
         client_name=${ost_name}_ecc
     fi
     ec=`get_devno $host echo_client $client_name`
     if [ -n "$ec" ]; then
-	echo $ec $client_name $client_name >&8
-	exit 0
+	echo $ec $client_name $client_name
+	return
     fi
     if [ -z "$ost_name" ]; then
-	echo "no echo client and ost_name not set, client:" \
-            "$client_name, host: $host"
-	exit 1
+	echo "no echo client and ost_name not set, client: $client_name, host: $host" 1>&2
+	return
     fi
     ost=`get_devno $host obdfilter $ost_name`
     if [ -z "$ost" ]; then
-	echo "OST $ost_name not setup"
-	exit 1
+	echo "OST $ost_name not setup" 1>&2
+	return
     fi
     client_name=${ost_name}_ecc
     remote_shell $host "$lctl <<EOF
@@ -288,11 +284,10 @@ get_ec_devno () {
 EOF"
     ec=`get_devno $host echo_client $client_name`
     if [ -z "$ec" ]; then
-	echo "Can't setup echo-client"
-	exit 1
+	echo "Can't setup echo-client" 1>&2
+	return
     fi
-    echo $ec $client_name 1 >&8
-    exit 0
+    echo $ec $client_name 1
 }
 
 # Create echo-clients using osc_names and osc_uuid
